### ISSUE TITLE
Save host config in a better way

### ISSUE THREAD

**Issue by SilverBut** [IDArlingTeam/IDArling#21]
Currently, host config is separately saved in several variables, which makes adding config items harder, such as client-side certificate verify, or keep-alive.
Maybe save them in a `dict` is better? Any recommendation/suggestion?

**Comment by NeatMonster** [comment]
Not sure I understood you correctly. You would like to replace the namedtuple [`Server`](https://github.com/IDArlingTeam/IDArling/blob/5471abd282d82850b9ef5e8b15d6ad6b6cecf9d4/idarling/core/core.py#L249) by a dictionary so that future improvements (mutual authentication/keep-alive) are easier to implement?

**Comment by NeatMonster** [comment]
Okay, I just saw [your recent commits](https://github.com/SilverBut/IDArling) and I see why it can be problematic when you add multiple options. A dictionary would definitively be better fitted for the task.

**Comment by SilverBut** [comment]
Yes, but I'm still wondering how to do it nicely. Now I'm planning to:
* Replace namedtuple `Server` to a dict, and also
* Rename `state.json` to `config.json` since we need to add more settings in it, and convert old `state.json` should be manually finished by the user

I'll try to do it in this weekend if no more ideas left here.

**Comment by NyaMisty** [comment]
I think that would also be a good idea to use a dict.
(As the python object is indeed dict-like)

**Comment by patateqbool** [comment]
Yes, it would definitely be better. The next feature that will be pushed (real-time synchronization of cursors) suffered from this problem too (in terms of the persistence of user configurations).

**Comment by NeatMonster** [comment]
Fixed by @SilverBut in https://github.com/IDArlingTeam/IDArling/pull/28. Closing...
