### ISSUE TITLE
Hook "Create struct from selection"

### ISSUE THREAD

**Issue by patateqbool** [IDArlingTeam/IDArling#22]
Create a struct from selection doesn't trigger a hook. We need to find a way to hook it (if possible)

**Comment by NyaMisty** [comment]
I remembered that the `create a struct` are in fact adding it to the local types, and won’t get into structs list until being used. 
As the local types sync has been implemented, I think this issue has already been fixed ;)

**Comment by patateqbool** [comment]
I just tested, actually the create struct from selection trigger effectively a change of local type, thank you for the fix!
The only problem here is an UI problem, on one side the user creating the structure sees it as defined in the struct view, while the remote users have to import the structure, and they are not necessarily aware about its existence without reading the logs...

**Comment by NeatMonster** [comment]
@patateqbool @NyaMisty What is the status of this issue? As far as I understand, some work is still needed, could you confirm? Thanks!

**Comment by patateqbool** [comment]
As @NyaMisty said, if the type is used by an user, it will be automatically imported by IDA in the struct view... I think we can say it's close now.
Please feel free to re-open the issue if you disagree @NyaMisty.
