### ISSUE TITLE
Implement general settings

### ISSUE THREAD

**Issue by patateqbool** [IDArlingTeam/IDArling#23]
We currently only have one menu for anything network-related. A general settings menu is necessary to allow the user to configure things like its username, log level, et cetera.

**Comment by patateqbool** [comment]
Currently working on with the cursor synchronization, will be pushed soon.

**Comment by SilverBut** [comment]
Maybe we can have a checklist for settings menu:

- [ ]  Network settings
  - [ ] Hostname
  - [ ] Port
  - [ ] Server SSL Config
    - [ ] No SSL
    - [ ] System CA
    - [ ] Customized CA
  - [ ] Client SSL Config
    - [ ] No Client-side Certificate
    - [ ] Customized Certificate
  - [ ] Keepalive
    - [ ] Retry every _ seconds
- [ ] General
  - [ ] Logging Level

BTW, maybe some configurations which are not usually changed (since debug level) might can be just put into the config file, without leaving a menu.

**Comment by NeatMonster** [comment]
> BTW, maybe some configurations which are not usually changed (since debug level) might can be just put into the config file, without leaving a menu.

I think the log level has its place in the menus, at least until IDArling is out of beta. I'm sure there are many bugs out there and having a way to toggle debug without editing a file doesn't sounds like a luxury.

**Comment by SilverBut** [comment]
@NeatMonster Besides. Do you think we should use a QML file instead of lots of `addWidget` in the script to simplify the GUI design? The code seems too dirty now...

**Comment by NeatMonster** [comment]
If we can get rid of Qt's verbosity, I'm all for it. I've just never looked into QML files, so that's why I never bothered with them.

**Comment by SilverBut** [comment]
Just created issue #32 for using QML. New setting dialog will be implemented after #32 closed.

**Comment by patateqbool** [comment]
Done except "User Settings" to "General Settings" in commit 3f25dc077fe8d8f592b3ee7f97540973b8599cde

**Comment by NeatMonster** [comment]
@patateqbool And except the icon... ;-)

**Comment by NeatMonster** [comment]
I think it's finally time to close this issue. :-)
