### ISSUE TITLE
Auto-analysis & Auto-saving

### ISSUE THREAD

**Issue by patateqbool** [IDArlingTeam/IDArling#26]
Implementing some kind of an auto-save is needed to: 
- avoid sending all the events since the first upload of the IDB
- avois sending them during a desynchronization when repulling is needed.

Also related, we should figure out what to do during IDA's auto-analysis. During the initial auto-analysis, event sending should probably be disabled. During later analyses, maybe we can keep it running?

**Comment by NyaMisty** [comment]
I suggest that we should tell users to save the IDB after the initial auto analysis in the usage.

**Comment by NeatMonster** [comment]
> I suggest that we should tell users to save the IDB after the initial auto analysis in the usage.

Yeah, that's what we were going for initially. Good to see everyone agrees. :-)
