### ISSUE TITLE
Implement user cursors

### ISSUE THREAD

**Issue by NeatMonster** [IDArlingTeam/IDArling#29]
User cursors allow users to follow collaborators working on the same project.

There a 3 kinds of cursors:
- Navband cursors;
- Function cursors;
- Disassembly cursors.

**Comment by patateqbool** [comment]
Working on, there is a bug with the navbar when there is too many segments, the whole navbar is colorized...
After talking with IDA staff, they agree to fix this in IDA 7.2.
For the moment, a checkbox allow the user to enable/disable the painter in the navbar.
Will be pushed soon.

**Comment by NeatMonster** [comment]
Reopening the issue to track the progress on letting the users change their username and color.

**Comment by NyaMisty** [comment]
Maybe we can also have a better color generator like this? [https://github.com/kevinwuhoo/randomcolor-py](https://github.com/kevinwuhoo/randomcolor-py)

**Comment by NeatMonster** [comment]
What is wrong with [the current one](https://github.com/IDArlingTeam/IDArling/blob/master/idarling/interface/painter.py#L50-#L51)? I designed it so that it keeps the saturation and lightness constant, and varies only the hue. As the result, the colors are both readable and vivid. Have you had any issue with it?

**Comment by NyaMisty** [comment]
Oh sorry I misunderstood your code. In this way I agree with you.
But for me, sometimes the cursor will generate colors like the following one, and when togethered with black font color it becomes quite hard for me to read it.
![image](https://user-images.githubusercontent.com/5344431/44559093-4e852f00-a77a-11e8-8a75-307871209ade.png)

**Comment by NyaMisty** [comment]
Well I lost the screenshot, but I remembered that when rendered in function list it make me crazy to read the function name :(

**Comment by patateqbool** [comment]
Users can change their username now (commit 6247dd9ebb7600b64f0f91cd095be75835a29153)

**Comment by patateqbool** [comment]
Users can now change their color (commit 6a990365), closing this issue.
