### ISSUE TITLE
TCP keepalive support

### ISSUE THREAD

**Issue by NyaMisty** [IDArlingTeam/IDArling#30]
I strongly suggest we implement the tcp keepalive.
De-synchronization are fatal for our plugin, but too often the connections are reset and the client won’t be notified until a long time passed. In these situation, the clients believe they are connected, but in fact they are already reset, leading to the de-sync.

**Comment by SilverBut** [comment]
Recommend use TCP keepalive with a reasonable timeout. Maybe can reduce some work?

**Comment by NyaMisty** [comment]
Some network like the one in the funny Caesars Palace will simple reset ** all ** connections every ~20s. I don't think TCP keepalive will help much in this situration.

**Comment by SilverBut** [comment]
> reset all connections every ~20s

Nothing will help much in this situation, except for throwing out a packet and caring nothing about its status.

But I would rather find a better ISP or use VPN. This is surely a network problem, instead of a jitter.

**Comment by NeatMonster** [comment]
@NyaMisty If we allow the user to configure the TCP keepalive, it might help. Judging from [this StackOverflow answer](https://stackoverflow.com/questions/12248132/how-to-change-tcp-keepalive-timer-using-python-script), you can set how long after the last packet keepalive packets will be sent, the interval between keepalive packets, and how many keepalives packets to send before closing the connection.

**Comment by NyaMisty** [comment]
OK I'll modify the issue
