### ISSUE TITLE
Implement notifications

### ISSUE THREAD

**Issue by NeatMonster** [IDArlingTeam/IDArling#42]
We should implement a notification system to show alerts to the user. One example of such notifications might be users joining/leaving the collaborative session.

**Comment by NeatMonster** [comment]
Here's what I've got:
![2018-08-28-003232_231x63_scrot](https://user-images.githubusercontent.com/775152/44690064-e4aaa500-aa59-11e8-8941-a3a80f731fe4.png)

The notification fades in and out, and is clickable. Any suggestion?

**Comment by hacksysteam** [comment]
This type of notification would be really distractive. How about in status bar? Just my opinion

**Comment by patateqbool** [comment]
@hacksysteam notifications can be disabled in settings.

**Comment by NeatMonster** [comment]
"Notifications" have been implemented in https://github.com/IDArlingTeam/IDArling/commit/791c92e907c7186daf5b90dcb64601c84dcc6904. Closing...
