### ISSUE TITLE
Switch to black/flake8 + extensions

### ISSUE THREAD

**Issue by NeatMonster** [IDArlingTeam/IDArling#48]
I would like to format the code using [`black`](https://github.com/ambv/black), but with a line length of 79 (confirming to PEP8).

Maybe we could switch to [`flake8`](https://github.com/PyCQA/flake8) to enforce the code-style, and use the following extensions:
- https://github.com/PyCQA/pep8-naming
- https://github.com/PyCQA/flake8-import-order
- https://github.com/PyCQA/flake8-docstrings

I'm not too sure about this though...

---

I want to, at least, remove all the useless comments (e.g. `:param arg: the arg`) from the code.

**Comment by hacksysteam** [comment]
@NeatMonster why not use pycharm, it has all the format thing you are looking for.

**Comment by patateqbool** [comment]
@hacksysteam I think we don't want to force users/developers to use an specific IDE.

**Comment by NeatMonster** [comment]
> I am strongly against the line length of 79. It's really frustrating sometime and I REALLY want to change it to line length 89 or 99.

The line length is not going to change. @patateqbool is using `vim` in his terminal so I don't want to go over 80 characters or it would become a lot less readable for him. But because manually fixing the formatting is a tedious task, I believe an automated tool like `black` brings a lot of good to the table.

**Comment by NeatMonster** [comment]
Here's what we've settled down on:
- using `black` for auto-formatting;
- checking code-style using `flake8` and
  - using the `pep8-naming` plugin;
  - using the `flake8-import-order` plugin.

Take a look at the file [`.travis.yml`](https://github.com/IDArlingTeam/IDArling/blob/master/.travis.yml) to see how to check code-style.
