### ISSUE TITLE
'module' object has no attribute 'SO_REUSEPORT'

### ISSUE THREAD

**Issue by cnsheds** [IDArlingTeam/IDArling#49]
windows7 ida7.0
'module' object has no attribute 'SO_REUSEPORT'

self._socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEPORT, 1)
AttributeError: 'module' object has no attribute 'SO_REUSEPORT'

'NoneType' object has no attribute 'setEnabled'
 File "D:/Tools/IDA 7.0/plugins\idarling\shared\discovery.py", line 130, in stop
    self._read_notifier.setEnabled(False)
AttributeError: 'NoneType' object has no attribute 'setEnabled'

**Comment by NeatMonster** [comment]
I guess `SO_REUSEPORT` is only necessary for macOS. Should be fixed in my latest commit.

Thanks a lot for the report @cnsheds!
