### ISSUE TITLE
Fix user experience broken by local type adding

### ISSUE THREAD

**Issue by patateqbool** [IDArlingTeam/IDArling#56]
The recent addition of local type has disrupted the creation of structure and structure members.
When adding a member to a structure, the structure is automatically collapsed.
A fix is needed.

**Comment by NyaMisty** [comment]
I'm sorry but I'm a little confused.
Do you mean you created a struct in local types and then adding the member to the structure?

I blindly guess it has something to do with my way to update the typeinfo

**Comment by patateqbool** [comment]
I c

**Comment by patateqbool** [comment]
Holly fuck, my phone is terrible, reopening this issue.
I create a structure in the structure view and add a member yes, that's all.
Yes I think also it's about typeinfo updating, but I've had no time to look yet.

**Comment by NyaMisty** [comment]
In fact I've looked through the SDK doc, and in fact there's several types of structures including mapped/copyof, but I can't find where it is exposed in the SDK :(

**Comment by patateqbool** [comment]
It seems to be fixed thanks to commit ff87c6539de44bed4e9cfb5eb1f76fc18836ab53, closing this issue.
