### ISSUE TITLE
Fix user name in navbar & add user name in func view

### ISSUE THREAD

**Issue by patateqbool** [IDArlingTeam/IDArling#57]
Just add nbytes for navbar and hook display hint for functions

**Comment by patateqbool** [comment]
Hi guys,

With @NeatMonster we have a dilemma.
Either we show a hint with the name of the user when a cursor is hover by the mouse at the cost of erasing the hint that IDA would display, or we do not display anything and we keep only the native hints of IDA.
What do you think ? @NyaMisty @deactivated @SilverBut

**Comment by NyaMisty** [comment]
Is that not fixable? Maybe we can contact the HexRays team first and ask if we can display the native hint and custom hint at the same time.

**Comment by patateqbool** [comment]
It's not. Yeah, I will do it today, the question is about what do we do if they can't fix or provide us a workaround right now ?

**Comment by NyaMisty** [comment]
I've got a simple idea. We can simply change the user's cursor to an addr other than basic block start. 
For example we can use NextAddr(cursor) to avoid overlapping with native hints

**Comment by NeatMonster** [comment]
@patateqbool I just pushed some event filtering code to add user hints to the functions window. I personally prefer to see IDA hints over user hints, even if that means that won't be able to have them in the disassembly view until IDA offers us a way to get the old hint.

@NyaMisty Not sure what you mean by that. I believe the cursor should be where the user is no matter what. If you're the talking about the color spanning over multiple lines in the disassembly at the beginning of a function, this is an IDA limitation and there is nothing we can do.

**Comment by NyaMisty** [comment]
I mean if we have a cursor pointing to the start of a function, we can instead print it on the next line, which won't affect the user experience in my opinion.

**Comment by patateqbool** [comment]
As Neat said, I believe the user's cursor must always tell his real position.
What's more, the hints that are displayed by IDA may be outside the beginning of a function, for example IDA displays a hint when using an XMM registry is done.
In my opinion, introducing a position glitch for all instructions or a hint to be displayed is a bug introduction.

**Comment by NeatMonster** [comment]
@NyaMisty I'm not sure we're on the same page on this issue. Let's consider a "call sub_xxx" instruction in the disassembly view. If you hover over the "sub_xxx" part, you'll see a preview of the function's beginning. Those are the native hints that would be replaced by an user's name if their cursor is on the same instruction. The question isn't really "should we put the cursors elsewhere" but "are we okay with replacing the native hints under those special conditions given that we have no way to avoid it".

**Comment by NyaMisty** [comment]
Well I understood in a wrong way. I thought we are discussing the situation of a cursor points to the function start (where the stack Vars are displayed)
If we are discussing the call xxx, then I totally agree with you ;)

**Comment by patateqbool** [comment]
The initial question was "are we okay with replacing the native hints under those special conditions given that we don't have a way to avoid it", aka when a cursor is on an instructions where a hint can ne displayed (call, XMM, etc...).
What's your opinion on it ? Keep the original hint or replace with the username until the user moves to another instruction ?

Btw, this issue will be closed after your answer, hints on navbar and func view have been introduced.

**Comment by NyaMisty** [comment]
If must one of it, I'll choose to "Keep the original hint"
But, I still wants to preserve both of them, can we achieve it by using some shortcuts? (For example press the Ctrl and Shift will disable our custom hint and show the native hint)

**Comment by NeatMonster** [comment]
That would work, but I'm not a big fan of this solution.

**Comment by NyaMisty** [comment]
Haha, I'm a big fan of a HexRays official solution ;)
