### ISSUE TITLE
Ask users before following them

### ISSUE THREAD

**Issue by patateqbool** [IDArlingTeam/IDArling#66]
Some users report us follow mode can be painful for the user followed.
Maybe we can add a demand to follow, or we can add a checkbox to disable cursors in the all views ?
cc @NeatMonster

**Comment by NeatMonster** [comment]
I don't like the idea of asking to an user if (s)he can be followed (it makes no sense to me). But if you want to implement some new settings to disable all the cursors, and to disable the cursors selectively, I'm all for it!

**Comment by patateqbool** [comment]
go for it mamène.

**Comment by patateqbool** [comment]
Done in develop branch.
