### ISSUE TITLE
Can't select an existing project when saving

### ISSUE THREAD

**Issue by roblabla** [IDArlingTeam/IDArling#72]
I'm running an IDArling server, and I noticed that it was impossible to save a database to an existing project. Clicking on them does not seem to trigger the `_project_clicked` function. I couldn't figure out the reason behind it.

![unknown](https://user-images.githubusercontent.com/1069318/47259927-ec168980-d4b1-11e8-834f-d199db83ed77.png)

**Comment by patateqbool** [comment]
Hi, it's the same idb that you're trying to save on a remote project?

**Comment by roblabla** [comment]
It's an IDB i never uploaded. Can a project not have multiple distinct databases? The fact that each project has a table of databases made me think it was just an organization thing.

**Comment by patateqbool** [comment]
A project can have multiple versions, just upload one time, then click on the project to upload a new version (database) of this project.
If you really want to open a new project, juste edit the idb name. :)

**Comment by roblabla** [comment]
I cannot click on the project. Only thing that works is clicking on "Create Project". If I click on any of the existing project (In the screenshot above, Switch300, FW100, w.e.), nothing happens.

I expected the database list to be populated with the db from t hat project, and the Create Database button to become available.

**Comment by roblabla** [comment]
OK, I think I understand. So a "Project" is tied to a single binary file, but can have multiple IDBs (all of them targeting the same file) ?

**Comment by patateqbool** [comment]
Yes.

**Comment by patateqbool** [comment]
Closing this issue, feel free to reopen it @roblabla if you still have questions.
